export const SCREEN_LABELS: Record<string, string> = {
  Dashboard:                  'Dashboard',
  // HR
  HR:                         'Human Resources',
  HumanManagement:            'Human Management',
  EmployeeManagement:         'Employee Management',
  UserManagement:             'User Management',
  CreateSystemUsers:          'Create System Users',
  AssignUserPermission:       'Assign User Permission',
  CreateUserRole:             'Create User Role',
  AssignUserRolePermission:   'Assign User Role Permission',
  // System Admin
  SystemAdmin:                'System Admin',
  SystemSettings:             'System Settings',
  GeneralSettings:            'General Settings',
  SystemDefaultSettings:      'System Default Settings',
  SupportTicket:              'Support Ticket',
  ActivityLog:                'Activity Log',
  SystemWorkFlow:             'System Work Flow',
  // Finance
  Finance:                    'Finance',
  FinanceUtilities:           'Finance Utilities',
  LedgerManagement:           'Ledger Management',
  FinanceOperation:           'Finance Operation',
  FinanceEntities:            'Entities',
  BusinessStructure:          'Business Structure',
  FinanceInstitutesAcc:       'Finance Institutes & Acc',
  BooksAndAccounts:           'Books & Accounts',
  UtilityService:             'Utility Service',
  ServiceProvider:            'Service Provider',
  TaxSettings:                'Tax Settings',
  POS:                        'POS',
  BankCardMachine:            'Create Bank Card Machine',
  LoyaltyPoints:              'Loyalty Points',
  ChartOfAccounts:            'Chart of Accounts',
  FinanceReportsGenerator:    'Finance Reports Generator',
  LedgerConnectionConsole:    'Ledger Connection Console',
  OpeningBalanceConsole:      'Opening Balance Console',
  JournalEntry:               'Journal Entry',
  ManagePOSPoints:            'Manage POS Points',
  SimpleInvoice:              'Simple Invoice',
  ManageBankCardMachine:      'Manage Bank Card Machine',
  // Procurement
  Procurement:                'Procurement',
  Purchasing:                 'Purchasing',
  StoresInventory:            'Stores & Inventory',
  Logistics:                  'Logistics',
};
